# config/packages/easy_admin.yaml
easy_admin:
  entities:
    # change the following to the namespaces of your own entities
    - App\Entity\Produit
    - App\Entity\Categorie
    - App\Entity\User
    - App\Entity\SousCategorie
