# config/packages/easy_admin.yaml
easy_admin:
  design:
    menu:
      - {label: "Entities"}
      - label: "categories"
        children:
          - {entity: Categorie, label: "categories list", icon: "th-list"}
          - {entity: Categorie, label: "ajouter une categorie", icon: "plus", params: {action: 'new'}}
      - label: "produit"
        children:
          - {entity: Produit, label: "produits   list", icon: "th-list"}
          - {entity: Produit, label: "ajouter un produit", icon: "plus", params: {action: 'new'}}
      - label: "utilisateur"
        children:
          - {entity: User, label: "utilisateurs list", icon: "th-list"}
          - {entity: User, label: "ajouter un utilisateur", icon: "plus", params: {action: 'new'}}
      - label: "sousCategorie"
        children:
          - {entity: SousCategorie, label: "SousCategories list", icon: "th-list"}
          - {entity: SousCategorie, label: "ajouter une SousCategorie", icon: "plus", params: {action: 'new'}}
  entities:
    # change the following to the namespaces of your own entities
    Produit:
      class: App\Entity\Produit
      label: "produit"
      form:
        fields:
          - nom
          - quantit
          - prix
          - description
          - {type: 'group', icon: 'clip', label: 'attachments', css_class: 'col-lg-5'}
          - {property: 'uploadedFile', type: 'vich_image'}

      list:
        collapse_actions: true
        actions: ['show','edit','delete']
        batch_actions: ['delete']
    Categorie:
      class: App\Entity\Categorie
      list:
        collapse_actions: true
        actions: ['show','edit','delete']
        batch_actions: ['delete']
    User:
      class: App\Entity\User
      list:
        collapse_actions: true
        actions: ['show','edit','delete']
        batch_actions: ['delete']

    SousCategorie:
      class: App\Entity\SousCategorie
      list:
        collapse_actions: true
        actions: ['show','edit','delete']
        batch_actions: ['delete']

